### ISSUE TITLE
Errors on website

### ISSUE THREAD

**Issue by anduck** [bitpay/bitcore-website#89]
https://bitcore.io/guides/bitcoin/ says:

cat "SHA256SUMS.asc" | grep "bitcoin-0.12.1-linux64.tar.gz"

should be:

cat SHA256SUMS.asc | grep "bitcoin-0.12.1-linux64.tar.gz"

also,

cd bitcoin-0.12.1
./bitcoind

should be

cd bitcoin-0.12.1/bin
./bitcoind

**Comment by braydonf** [comment]
Both `cat "SHA256SUMS.asc"` and `cat SHA256SUMS.asc` work here, updated in https://github.com/bitpay/bitcore-website/pull/90.

**Comment by anduck** [comment]
Looking good!
