### ISSUE TITLE
Link to Full Node Guide from Wallet Service Guide broken.

### ISSUE THREAD

**Issue by Ashaman-** [bitpay/bitcore-website#95]
It points to http://localhost:3000/guides/full-node
It should point to https://bitcore.io/guides/full-node/

Submitting PR with fix.

**Comment by braydonf** [comment]
Thanks, it looks like the PR isn't to this repository though.

**Comment by Ashaman-** [comment]
I realized that shortly after initially making it, and resubmitted it correctly - PR #96

**Comment by braydonf** [comment]
It's been merged
